### ISSUE TITLE
 No module named 'appdirs'

### ISSUE THREAD

**Issue by 1oglop1** [pablogsal/black-pycharm#8]
Black used to work without problem but now it started to complain about this, `appdirs` is installed in venv together with black, does anyone know what am I doing wrong?

```
BlackPycharm: Traceback (most recent call last): File "/Users/user/.pyenv/versions/3.7.2/bin/black", line 6, in   from black import main File "/Users/user/.pyenv/versions/3.7.2/lib/python3.7/site-packages/black.py", line 38, in   from appdirs import user_cache_dir ModuleNotFoundError: No module named 'appdirs'
```

**Comment by ByVassilios** [comment]
I have the same issue almost a year later.

**Comment by maxblumental** [comment]
Any updates? The problem is still present: both appdirs and black are in my venv (python3.6.13):
```
Traceback (most recent call last):
  File "~/anaconda3/envs/my_proj/bin/black", line 5, in <module>
    from black import patched_main
  File "~/anaconda3/envs/my_proj/lib/python3.6/site-packages/black.py", line 41, in <module>
    from appdirs import user_cache_dir
ModuleNotFoundError: No module named 'appdirs'
```
